/** Deterministic source-only render fixture. No packages, network or project execution.
 * Usage: node fixtures/generate-broad.mjs [moduleCount=1000]
 * Output: fixtures/generated-broad-N, never the built-in demo.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const count = Number(process.argv[2] ?? 1000);
if (!Number.isInteger(count) || count < 12 || count > 10000) {
  throw new Error('moduleCount must be an integer between 12 and 10000.');
}
const fixtures = dirname(fileURLToPath(import.meta.url));
const root = join(fixtures, `generated-broad-${count}`);
const names = ['foundation', 'types', 'platform', 'data', 'models', 'domain', 'repositories', 'services', 'features', 'widgets', 'pages', 'app'];
const weights = [96, 96, 96, 96, 92, 88, 88, 80, 76, 72, 64, 56];
const sizes = weights.map((weight) => Math.max(1, Math.floor(count * weight / 1000)));
let allocated = sizes.reduce((sum, size) => sum + size, 0);
for (let layer = 0; allocated < count; layer = (layer + 1) % names.length) { sizes[layer]++; allocated++; }
const layers = names.map((name, layer) => Array.from({ length: sizes[layer] }, (_, index) =>
  `src/${String(layer).padStart(2, '0')}-${name}/module-${String(index).padStart(4, '0')}.ts`));
let edges = 0;
for (let layer = 0; layer < layers.length; layer++) {
  for (let index = 0; index < layers[layer].length; index++) {
    const current = layers[layer][index];
    const dependencies = new Set();
    if (layer > 0) {
      dependencies.add(layers[layer - 1][index % sizes[layer - 1]]);
      dependencies.add(layers[layer - 1][(index * 7 + 3) % sizes[layer - 1]]);
      if (layer > 2 && index % 10 === 0) dependencies.add(layers[layer - 3][index % sizes[layer - 3]]);
    }
    edges += dependencies.size;
    const lines = [`/** Layer ${layer}: ${names[layer]}, fixture module ${index}. */`];
    for (const dependency of dependencies) {
      let relative = posix.relative(posix.dirname(current), dependency);
      if (!relative.startsWith('.')) relative = `./${relative}`;
      lines.push(`import '${relative}';`);
    }
    lines.push('', `export const moduleId = '${names[layer]}/${index}';`, '');
    for (let operation = 0; operation < 1 + ((index * 3 + layer) % 5); operation++) {
      lines.push(`export function operation${operation}(value: number) {`, `  return value + ${operation + layer};`, '}', '');
    }
    const destination = join(root, current);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, `${lines.join('\n')}\n`, 'utf8');
  }
}
const summary = { modules: count, edges, layers: layers.length, sizes, root };
writeFileSync(join(root, 'README.md'), `# Broad rendering fixture\n\n${count} TypeScript modules in ${layers.length} dependency layers.\n\nGenerated by fixtures/generate-broad.mjs; source files are never executed.\n`, 'utf8');
console.log(JSON.stringify(summary));
